#!/usr/bin/env bash
# client/install.sh — Install claw CLI, connect to oMLX server
# Called by: ./setup client [server-host] [port] [api-key]
#
# Reads:   ~/.claw/config/connection.env
# Writes:  ~/.claw/claw-env       (sourced via ~/.claw-env symlink)
# Links:   ~/.local/bin/claw      → built binary in repo .build/
#          ~/.claw-env             → ~/.claw/claw-env

set -euo pipefail

REPO_DIR="${1:?REPO_DIR required}"; shift

CLAW_HOME="$HOME/.claw"
CLAW_CONFIG="$CLAW_HOME/config"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ── Resolve server connection ────────────────────────────────────────
SERVER_HOST=""
SERVER_PORT="10741"
API_KEY=""
DEFAULT_MODEL="Qwen3-Coder-Next-4bit"

CONN_FILE="$CLAW_CONFIG/connection.env"
if [[ -f "$CONN_FILE" ]]; then
  info "Reading ~/.claw/config/connection.env"
  source "$CONN_FILE"
  SERVER_HOST="${CLAW_SERVER_HOST:-}"
  SERVER_PORT="${CLAW_SERVER_PORT:-10741}"
  API_KEY="${CLAW_API_KEY:-}"
  DEFAULT_MODEL="${CLAW_DEFAULT_MODEL:-Qwen3-Coder-Next-4bit}"
fi

SERVER_HOST="${1:-$SERVER_HOST}"
SERVER_PORT="${2:-$SERVER_PORT}"
API_KEY="${3:-$API_KEY}"

if [[ -z "$SERVER_HOST" ]]; then
  err "Server host required."
  err ""
  err "Either:"
  err "  1. scp connection.env from the server:"
  err "       scp server:~/.claw/config/connection.env ~/.claw/config/"
  err "  2. Pass as argument:  ./setup client <host> [port] [api-key]"
  exit 1
fi

SERVER_URL="http://${SERVER_HOST}:${SERVER_PORT}"
info "Server: $SERVER_URL"

OS="$(uname -s)"; ARCH="$(uname -m)"
info "Platform: $OS $ARCH"

# ── 1. Build dependencies ───────────────────────────────────────────
echo ""; info "Build dependencies..."

if [[ "$OS" == "Linux" ]]; then
  if command -v apt-get &>/dev/null; then
    DEPS="build-essential pkg-config libssl-dev git curl"
    MISSING=""
    for dep in $DEPS; do dpkg -s "$dep" &>/dev/null || MISSING="$MISSING $dep"; done
    if [[ -n "$MISSING" ]]; then
      info "Installing:$MISSING"
      sudo apt-get update -qq; sudo apt-get install -y -qq $MISSING
    fi
  elif command -v dnf &>/dev/null; then
    sudo dnf install -y gcc pkg-config openssl-devel git curl
  elif command -v pacman &>/dev/null; then
    sudo pacman -S --needed --noconfirm base-devel openssl git curl
  else
    warn "Unknown package manager — ensure gcc, pkg-config, libssl-dev, git, curl are installed."
  fi
elif [[ "$OS" == "Darwin" ]]; then
  xcode-select -p &>/dev/null || { xcode-select --install 2>/dev/null || true; warn "Complete Xcode CLI install, then re-run."; }
fi
ok "Dependencies ready"

# ── 2. Rust ──────────────────────────────────────────────────────────
echo ""; info "Rust toolchain..."
if command -v rustc &>/dev/null && command -v cargo &>/dev/null; then
  ok "Rust $(rustc --version | awk '{print $2}')"
else
  info "Installing Rust..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  source "$HOME/.cargo/env"
  ok "Rust installed"
fi
export PATH="$HOME/.cargo/bin:$PATH"

# ── 3. Clone / update claw-code-local ────────────────────────────────
echo ""
CLAW_SRC="$REPO_DIR/.build/claw-code-local"
info "Source: $CLAW_SRC"

if [[ -d "$CLAW_SRC/.git" ]]; then
  info "Updating..."
  cd "$CLAW_SRC"; git pull --ff-only 2>/dev/null || warn "Pull failed — building existing"
else
  mkdir -p "$(dirname "$CLAW_SRC")"
  git clone https://github.com/codetwentyfive/claw-code-local.git "$CLAW_SRC"
fi
ok "Source ready"

# ── 4. Build ─────────────────────────────────────────────────────────
echo ""; info "Building claw CLI (release)..."
cd "$CLAW_SRC/rust"
cargo build -p rusty-claude-cli --release 2>&1 | tail -3

CLAW_BIN=""
for c in "$CLAW_SRC/rust/target/release/claw" "$CLAW_SRC/rust/target/release/claw-cli"; do
  [[ -f "$c" && -x "$c" ]] && { CLAW_BIN="$c"; break; }
done
if [[ -z "$CLAW_BIN" ]]; then
  if [[ "$OS" == "Darwin" ]]; then
    CLAW_BIN="$(find "$CLAW_SRC/rust/target/release" -maxdepth 1 -perm +111 -type f -name 'claw*' 2>/dev/null | head -1)"
  else
    CLAW_BIN="$(find "$CLAW_SRC/rust/target/release" -maxdepth 1 -executable -type f -name 'claw*' 2>/dev/null | head -1)"
  fi
fi
[[ -n "$CLAW_BIN" ]] || { err "Build failed — no claw binary found."; exit 1; }
ok "Built: $CLAW_BIN"

# ── 5. Symlink binary ───────────────────────────────────────────────
echo ""; info "Linking binary..."
BIN_DIR="$HOME/.local/bin"; mkdir -p "$BIN_DIR"
rm -f "$BIN_DIR/claw"
ln -sf "$CLAW_BIN" "$BIN_DIR/claw"
ok "~/.local/bin/claw → $CLAW_BIN"

# ── 6. Generate env file in ~/.claw/, symlink to ~/.claw-env ─────────
echo ""; info "Writing environment..."
CLAW_ENV="$CLAW_HOME/claw-env"

cat > "$CLAW_ENV" <<ENV_EOF
# Claw Code — oMLX server connection
# Generated by ./setup client on $(date -Iseconds)
# Lives at ~/.claw/claw-env, symlinked to ~/.claw-env
# To change: edit ~/.claw/config/connection.env, then re-run ./setup client

export CLAW_HOME="$CLAW_HOME"

# Local oMLX server — all models run locally, zero API cost
export OPENAI_API_KEY="${API_KEY:-dummy}"
export OPENAI_BASE_URL="${SERVER_URL}/v1"
export CLAW_DEFAULT_MODEL="gemma-4-31b-it-8bit"
export CLAW_CODER_MODEL="Qwen3-Coder-Next-4bit"
export CLAW_REVIEWER_MODEL="gemma-4-31b-it-8bit"

# PATH
export PATH="\$HOME/.local/bin:\$HOME/.cargo/bin:\$PATH"

# Model shortcuts — wrap claw to resolve short names
claw() {
  local model_arg=""
  case "\$1" in
    code|coder)   shift; command claw --model "\$CLAW_CODER_MODEL" "\$@"; return ;;
    review|reason) shift; command claw --model "\$CLAW_REVIEWER_MODEL" "\$@"; return ;;
    fast)          shift; command claw --model gemma-4-26b-a4b-it-4bit "\$@"; return ;;
    general)       shift; command claw --model Qwen3.5-27B-4bit "\$@"; return ;;
    status)        curl -s -H "Authorization: Bearer \${OPENAI_API_KEY}" ${SERVER_URL}/v1/models | python3 -m json.tool; return ;;
    ping)          curl -sf -H "Authorization: Bearer \${OPENAI_API_KEY}" ${SERVER_URL}/v1/models >/dev/null && echo "oMLX: OK" || echo "oMLX: UNREACHABLE"; return ;;
  esac
  command claw "\$@"
}
ENV_EOF

rm -f "$HOME/.claw-env"
ln -sf "$CLAW_ENV" "$HOME/.claw-env"
ok "~/.claw-env → ~/.claw/claw-env"

# ── 7. Shell profile hook ────────────────────────────────────────────
echo ""; info "Shell profile..."
MARKER="# >>> claw >>>"
SNIPPET='[ -f "$HOME/.claw-env" ] && source "$HOME/.claw-env"'

for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [[ -f "$rc" ]] || continue
  if grep -qF "$MARKER" "$rc" 2>/dev/null; then
    ok "Already in $(basename "$rc")"
  else
    printf '\n%s\n%s\n# <<< claw <<<\n' "$MARKER" "$SNIPPET" >> "$rc"
    ok "Added to $(basename "$rc")"
  fi
done

source "$CLAW_ENV"

# ── 8. Test ──────────────────────────────────────────────────────────
echo ""; info "Testing connection..."
AUTH_HEADER=""
[[ -n "${API_KEY:-}" ]] && AUTH_HEADER="Authorization: Bearer ${API_KEY}"
if curl -sf ${AUTH_HEADER:+-H "$AUTH_HEADER"} "${SERVER_URL}/v1/models" >/dev/null 2>&1; then
  ok "Server reachable at $SERVER_URL"
  curl -s ${AUTH_HEADER:+-H "$AUTH_HEADER"} "${SERVER_URL}/v1/models" 2>/dev/null \
    | python3 -c "import json,sys
for m in json.load(sys.stdin).get('data',[]): print(f'         • {m[\"id\"]}')" 2>/dev/null || true
else
  warn "Server not reachable at $SERVER_URL"
  warn "Ensure oMLX is running and port ${SERVER_PORT} is open."
fi

# ── Summary ──────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Client setup complete"
echo ""
echo "  source ~/.claw-env    # or open a new shell"
echo ""
echo "  claw                          # REPL"
echo "  claw --model <name> \"prompt\"  # one-shot"
echo "  claw-coder / claw-review / claw-general / claw-fast"
echo "  claw-status / claw-ping"
echo ""
info "  Config:   ~/.claw/config/"
info "  Update:   git pull && ./setup client"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
