#!/usr/bin/env bash
# server/install.sh — Bootstrap oMLX on the M2 Ultra
# Called by: ./setup server [--skip-models] [--rotate-key] [--dry-run]
#
# Reads:   ~/.claw/config/omlx-server.env
#          ~/.claw/config/models.json
# Writes:  ~/.claw/settings.json
#          ~/.claw/api_key
#          ~/.claw/config/connection.env
#          ~/.claw/cache/  ~/.claw/logs/
#          ~/Library/LaunchAgents/com.claw.omlx-server.plist  (symlink)

set -euo pipefail

REPO_DIR="${1:?REPO_DIR required}"; shift

CLAW_HOME="$HOME/.claw"
CLAW_CONFIG="$CLAW_HOME/config"

SKIP_MODELS=false; DRY_RUN=false; ROTATE_KEY=false
for arg in "$@"; do
  case "$arg" in
    --skip-models) SKIP_MODELS=true ;;
    --dry-run)     DRY_RUN=true ;;
    --rotate-key)  ROTATE_KEY=true ;;
  esac
done

# ── Source config from ~/.claw/config/ ───────────────────────────────
if [[ ! -f "$CLAW_CONFIG/omlx-server.env" ]]; then
  echo "ERROR: $CLAW_CONFIG/omlx-server.env not found" >&2; exit 1
fi
source "$CLAW_CONFIG/omlx-server.env"

if [[ ! -f "$CLAW_CONFIG/models.json" ]]; then
  echo "ERROR: $CLAW_CONFIG/models.json not found" >&2; exit 1
fi

# ── Colours ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
run()   { if $DRY_RUN; then echo -e "${YELLOW}[DRY]${NC} $*"; else "$@"; fi; }

# ── Pre-flight ───────────────────────────────────────────────────────
info "Pre-flight checks..."
[[ "$(uname -s)" == "Darwin" ]] || { err "macOS required"; exit 1; }
[[ "$(uname -m)" == "arm64"  ]] || { err "Apple Silicon required"; exit 1; }
command -v brew &>/dev/null      || { err "Homebrew required"; exit 1; }

RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
ok "macOS arm64, ${RAM_GB} GB RAM"

# ── 1. Install oMLX ─────────────────────────────────────────────────
echo ""; info "Installing oMLX..."
if command -v omlx &>/dev/null; then
  ok "oMLX present — upgrading"
  run brew update; run brew upgrade omlx 2>/dev/null || true
else
  run brew tap jundot/omlx https://github.com/jundot/omlx
  run brew install omlx
fi
ok "oMLX ready"

# ── 2. Resolve oMLX's bundled Python (has huggingface_hub) ──────────
OMLX_BIN_PATH="$(command -v omlx || echo "/opt/homebrew/bin/omlx")"
OMLX_PYTHON="$(head -1 "$OMLX_BIN_PATH" | sed 's/^#!//')"
if [[ -x "$OMLX_PYTHON" ]]; then
  ok "oMLX Python: $OMLX_PYTHON"
else
  OMLX_PYTHON="python3"
  warn "Could not find oMLX's bundled Python, falling back to system python3"
fi

# ── 3. Directories ──────────────────────────────────────────────────
echo ""; info "Creating directories..."
run mkdir -p "$OMLX_MODEL_DIR"
run mkdir -p "$CLAW_HOME/cache"
run mkdir -p "$CLAW_HOME/logs"

# ── 4. API key ───────────────────────────────────────────────────────
KEYFILE="$CLAW_HOME/api_key"
if $ROTATE_KEY || [[ ! -f "$KEYFILE" ]]; then
  STABLE_API_KEY="claw-$(openssl rand -hex 16)"
  if ! $DRY_RUN; then
    echo "$STABLE_API_KEY" > "$KEYFILE"; chmod 600 "$KEYFILE"
  fi
  ok "Generated new API key → $KEYFILE"
else
  STABLE_API_KEY="$(cat "$KEYFILE")"
  info "Using existing API key"
fi

# ── 5. oMLX settings.json ───────────────────────────────────────────
echo ""; info "Writing oMLX settings..."
SSD_CACHE="${OMLX_SSD_CACHE_DIR:-$CLAW_HOME/cache}"

if ! $DRY_RUN; then
  cat > "$CLAW_HOME/settings.json" <<EOF
{
  "model_dir": "$OMLX_MODEL_DIR",
  "host": "$OMLX_HOST",
  "port": $OMLX_PORT,
  "api_key": "$STABLE_API_KEY",
  "max_process_memory": "$OMLX_MAX_PROCESS_MEMORY",
  "max_model_memory": "$OMLX_MAX_MODEL_MEMORY",
  "paged_ssd_cache_dir": "$SSD_CACHE",
  "hot_cache_max_size": "$OMLX_HOT_CACHE_MAX_SIZE",
  "max_num_seqs": $OMLX_MAX_NUM_SEQS
}
EOF
fi
ok "~/.claw/settings.json"

# ── 6. connection.env for clients ────────────────────────────────────
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || echo "$(hostname).local")

if ! $DRY_RUN; then
  cat > "$CLAW_CONFIG/connection.env" <<EOF
# Generated by ./setup server on $(date -Iseconds)
# scp this file to client machines: ~/.claw/config/connection.env
CLAW_SERVER_HOST="${LOCAL_IP}"
CLAW_SERVER_PORT="${OMLX_PORT}"
CLAW_API_KEY="${STABLE_API_KEY}"
CLAW_DEFAULT_MODEL="${OMLX_DEFAULT_MODEL}"
EOF
  chmod 600 "$CLAW_CONFIG/connection.env"
fi
ok "~/.claw/config/connection.env"

# ── 7. Download models ──────────────────────────────────────────────
echo ""
if $SKIP_MODELS; then
  warn "Skipping model downloads (--skip-models)"
else
  info "Downloading models (using oMLX's bundled huggingface_hub)..."
  "$OMLX_PYTHON" -c "
import json, os, sys
with open('$CLAW_CONFIG/models.json') as f:
    data = json.load(f)
for m in data['models']:
    print(m['hf_repo'] + '|' + m['id'])
" | while IFS='|' read -r repo mid; do
    local_path="$OMLX_MODEL_DIR/$mid"
    if [[ -d "$local_path" ]] && ls "$local_path"/*.safetensors &>/dev/null 2>&1; then
      ok "Present: $mid"
    else
      info "Downloading $repo → $mid"
      if ! $DRY_RUN; then
        "$OMLX_PYTHON" -c "
from huggingface_hub import snapshot_download
snapshot_download('$repo', local_dir='$local_path')
"
      fi
    fi
  done
fi

# ── 8. launchd plist (generated → ~/.claw/, symlinked into LaunchAgents)
echo ""; info "Setting up launchd service..."
OMLX_BIN="$OMLX_BIN_PATH"
GENERATED_PLIST="$CLAW_HOME/com.claw.omlx-server.plist"

if ! $DRY_RUN; then
  cat > "$GENERATED_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.claw.omlx-server</string>
  <key>ProgramArguments</key>
  <array>
    <string>${OMLX_BIN}</string>
    <string>serve</string>
    <string>--model-dir</string>
    <string>${OMLX_MODEL_DIR}</string>
    <string>--host</string>
    <string>${OMLX_HOST}</string>
    <string>--port</string>
    <string>${OMLX_PORT}</string>
    <string>--max-process-memory</string>
    <string>${OMLX_MAX_PROCESS_MEMORY}</string>
    <string>--max-model-memory</string>
    <string>${OMLX_MAX_MODEL_MEMORY}</string>
    <string>--paged-ssd-cache-dir</string>
    <string>${SSD_CACHE}</string>
    <string>--hot-cache-max-size</string>
    <string>${OMLX_HOT_CACHE_MAX_SIZE}</string>
    <string>--max-num-seqs</string>
    <string>${OMLX_MAX_NUM_SEQS}</string>
    <string>--api-key</string>
    <string>${STABLE_API_KEY}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${CLAW_HOME}/logs/omlx-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${CLAW_HOME}/logs/omlx-stderr.log</string>
  <key>WorkingDirectory</key>
  <string>${HOME}</string>
</dict>
</plist>
PLIST
fi

PLIST_LINK="$HOME/Library/LaunchAgents/com.claw.omlx-server.plist"
mkdir -p "$HOME/Library/LaunchAgents"
if ! $DRY_RUN; then
  launchctl unload "$PLIST_LINK" 2>/dev/null || true
  rm -f "$PLIST_LINK"
  ln -sf "$GENERATED_PLIST" "$PLIST_LINK"
  launchctl load "$PLIST_LINK"
fi
ok "launchd: $PLIST_LINK → $GENERATED_PLIST"

# ── Summary ──────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ok "Server setup complete"
echo ""
info "  oMLX:     http://${LOCAL_IP}:${OMLX_PORT}"
info "  Admin:    http://${LOCAL_IP}:${OMLX_PORT}/admin"
info "  API key:  $(cat "$KEYFILE")"
info "  Config:   ~/.claw/config/"
info "  Logs:     ~/.claw/logs/"
echo ""
info "  Test:  curl -s -H 'Authorization: Bearer \$(cat ~/.claw/api_key)' http://localhost:${OMLX_PORT}/v1/models | python3 -m json.tool"
echo ""
info "  For clients, copy the connection file:"
info "    scp ~/.claw/config/connection.env <host>:~/.claw/config/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
