#!/usr/bin/env bash
# server/install.sh — Bootstrap oMLX on the M2 Ultra
# Called by: ./setup server
# All paths reference $REPO_DIR so git pull updates everything in place.

set -euo pipefail

REPO_DIR="${1:?REPO_DIR required}"
shift

# ── Flags ────────────────────────────────────────────────────────────
SKIP_MODELS=false
DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --skip-models) SKIP_MODELS=true ;;
    --dry-run)     DRY_RUN=true ;;
  esac
done

# ── Source config ────────────────────────────────────────────────────
source "$REPO_DIR/config/omlx-server.env"

# ── Colours ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

run() { if $DRY_RUN; then echo -e "${YELLOW}[DRY]${NC} $*"; else "$@"; fi; }

# ── Pre-flight ───────────────────────────────────────────────────────
info "Pre-flight checks..."

[[ "$(uname -s)" == "Darwin" ]]  || { err "macOS required"; exit 1; }
[[ "$(uname -m)" == "arm64"  ]]  || { err "Apple Silicon required"; exit 1; }
command -v brew &>/dev/null       || { err "Homebrew required — https://brew.sh"; exit 1; }

RAM_GB=$(( $(sysctl -n hw.memsize) / 1073741824 ))
ok "macOS arm64, ${RAM_GB} GB RAM"

# ── 1. Install oMLX ─────────────────────────────────────────────────
echo ""
info "Installing oMLX..."

if command -v omlx &>/dev/null; then
  ok "oMLX present — upgrading"
  run brew update && run brew upgrade omlx 2>/dev/null || true
else
  run brew tap jundot/omlx https://github.com/jundot/omlx
  run brew install omlx
fi

ok "oMLX ready"

# ── 2. huggingface-cli ──────────────────────────────────────────────
echo ""
info "Ensuring huggingface-cli..."

if ! command -v huggingface-cli &>/dev/null; then
  pip3 install --break-system-packages -q huggingface_hub[cli] 2>/dev/null \
    || pip3 install -q huggingface_hub[cli] 2>/dev/null \
    || warn "pip3 install failed — download models via oMLX admin UI instead"
fi

# ── 3. Directories ──────────────────────────────────────────────────
echo ""
info "Creating directories..."
run mkdir -p "$OMLX_MODEL_DIR"
run mkdir -p "$OMLX_SSD_CACHE_DIR"
run mkdir -p "$HOME/.omlx/logs"

# ── 4. API key (generate once, persist) ──────────────────────────────
KEYFILE="$HOME/.omlx/api_key"
if [[ -f "$KEYFILE" ]]; then
  STABLE_API_KEY="$(cat "$KEYFILE")"
  info "Using existing API key"
else
  STABLE_API_KEY="claw-$(openssl rand -hex 16)"
  if ! $DRY_RUN; then
    echo "$STABLE_API_KEY" > "$KEYFILE"
    chmod 600 "$KEYFILE"
  fi
  ok "Generated API key → $KEYFILE"
fi

# ── 5. Write oMLX settings.json ─────────────────────────────────────
echo ""
info "Writing oMLX settings..."

if ! $DRY_RUN; then
  cat > "$HOME/.omlx/settings.json" <<EOF
{
  "model_dir": "$OMLX_MODEL_DIR",
  "host": "$OMLX_HOST",
  "port": $OMLX_PORT,
  "api_key": "$STABLE_API_KEY",
  "max_process_memory": "$OMLX_MAX_PROCESS_MEMORY",
  "max_model_memory": "$OMLX_MAX_MODEL_MEMORY",
  "paged_ssd_cache_dir": "$OMLX_SSD_CACHE_DIR",
  "hot_cache_max_size": "$OMLX_HOT_CACHE_MAX_SIZE",
  "max_concurrent_requests": $OMLX_MAX_CONCURRENT_REQUESTS
}
EOF
fi
ok "~/.omlx/settings.json"

# ── 6. Write connection.env for clients ──────────────────────────────
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || echo "$(hostname).local")
CONNECTION_FILE="$REPO_DIR/config/connection.env"

if ! $DRY_RUN; then
  cat > "$CONNECTION_FILE" <<EOF
# Generated by ./setup server on $(date -Iseconds)
# Copy this file to client clones: config/connection.env
CLAW_SERVER_HOST="${LOCAL_IP}"
CLAW_SERVER_PORT="${OMLX_PORT}"
CLAW_API_KEY="${STABLE_API_KEY}"
CLAW_DEFAULT_MODEL="${OMLX_DEFAULT_MODEL}"
EOF
  chmod 600 "$CONNECTION_FILE"
fi
ok "config/connection.env (gitignored — scp to clients)"

# ── 7. Download models ──────────────────────────────────────────────
echo ""
if $SKIP_MODELS; then
  warn "Skipping model downloads (--skip-models)"
else
  info "Downloading models (this may take a while)..."

  python3 -c "
import json
with open('$REPO_DIR/config/models.json') as f:
    data = json.load(f)
for m in data['models']:
    print(m['hf_repo'] + '|' + m['id'])
" | while IFS='|' read -r repo mid; do
    local_path="$OMLX_MODEL_DIR/$mid"
    if [[ -d "$local_path" ]] && ls "$local_path"/*.safetensors &>/dev/null 2>&1; then
      ok "Already downloaded: $mid"
    else
      info "Downloading $repo → $mid"
      if command -v huggingface-cli &>/dev/null && ! $DRY_RUN; then
        huggingface-cli download "$repo" --local-dir "$local_path" --local-dir-use-symlinks False
      else
        warn "  → Download manually or via oMLX admin UI at http://localhost:${OMLX_PORT}/admin"
      fi
    fi
  done
fi

# ── 8. Symlink launchd plist ─────────────────────────────────────────
echo ""
info "Setting up launchd service..."

# Generate the plist from the template
GENERATED_PLIST="$REPO_DIR/server/com.claw.omlx-server.plist"
OMLX_BIN="$(command -v omlx || echo "/opt/homebrew/bin/omlx")"

if ! $DRY_RUN; then
  cat > "$GENERATED_PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.claw.omlx-server</string>
  <key>ProgramArguments</key>
  <array>
    <string>${OMLX_BIN}</string>
    <string>serve</string>
    <string>--model-dir</string>
    <string>${OMLX_MODEL_DIR}</string>
    <string>--host</string>
    <string>${OMLX_HOST}</string>
    <string>--port</string>
    <string>${OMLX_PORT}</string>
    <string>--max-process-memory</string>
    <string>${OMLX_MAX_PROCESS_MEMORY}</string>
    <string>--max-model-memory</string>
    <string>${OMLX_MAX_MODEL_MEMORY}</string>
    <string>--paged-ssd-cache-dir</string>
    <string>${OMLX_SSD_CACHE_DIR}</string>
    <string>--hot-cache-max-size</string>
    <string>${OMLX_HOT_CACHE_MAX_SIZE}</string>
    <string>--max-concurrent-requests</string>
    <string>${OMLX_MAX_CONCURRENT_REQUESTS}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>OMLX_API_KEY</key>
    <string>${STABLE_API_KEY}</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${HOME}/.omlx/logs/omlx-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>${HOME}/.omlx/logs/omlx-stderr.log</string>
  <key>WorkingDirectory</key>
  <string>${HOME}</string>
</dict>
</plist>
PLIST_EOF
fi

# Symlink into LaunchAgents
PLIST_LINK="$HOME/Library/LaunchAgents/com.claw.omlx-server.plist"
mkdir -p "$HOME/Library/LaunchAgents"

if ! $DRY_RUN; then
  launchctl unload "$PLIST_LINK" 2>/dev/null || true
  rm -f "$PLIST_LINK"
  ln -sf "$GENERATED_PLIST" "$PLIST_LINK"
  launchctl load "$PLIST_LINK"
fi

ok "launchd: $PLIST_LINK → $GENERATED_PLIST"
info "git pull + ./setup server will regenerate and reload the plist"

# ── Summary ──────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
ok "Server setup complete"
echo ""
info "  oMLX:       http://${LOCAL_IP}:${OMLX_PORT}"
info "  Admin UI:   http://${LOCAL_IP}:${OMLX_PORT}/admin"
info "  API key:    $(cat "$KEYFILE")"
info "  Logs:       ~/.omlx/logs/"
echo ""
info "  Test:  curl -s http://localhost:${OMLX_PORT}/v1/models | python3 -m json.tool"
echo ""
info "  For clients, copy config/connection.env to their repo clones:"
info "    scp $CONNECTION_FILE <client>:$(basename "$REPO_DIR")/config/connection.env"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
